Added option to allow items in table to be selected
ngOfficeUIFabric/ng-officeuifabric pull request #464
Opened 2017-01-18 14:04 UTC by emilverwoerd

Changed uif-table and added property uif-selected-items which allows to get information about the selected records in the table

2017-02-06 13:17 UTC, andrewconnell requested changes
Thanks for the new feature, but there are two things that need to be addressed with this PR before we can merge it in.

1. Update the JSDOC's for the interfaces that you added properties for.
1. Update the demo to reflect the new functionality that you added.

Without these two changes, this feature is not visible to consumers unless they poke around the source code and tests. Document the enhancement please.

2017-02-06 13:17 UTC, andrewconnell commented on src/components/table/tableDirective.ts
> +  selectedItems: any;
Please add documentation in the JSDOC for this interface to document this property.

2017-02-06 13:17 UTC, andrewconnell commented on src/components/table/tableDirective.ts
> +  uifSelectedItems?: any;
Please add documentation in the JSDOC for this interface to document this property.

2017-02-07 09:17 UTC, emilverwoerd commented
Going to implement the requested changes. Also the examples are faulty with the controller on a <p> tag will fix that also.

2017-02-08 10:32 UTC, andrewconnell approved these changes

2017-02-08 11:06 UTC, closed without merging

2017-02-08 11:39 UTC, emilverwoerd commented
Hi Andrew thanks for adding but is there a reason why the .spec file isn't updated

2017-02-08 11:51 UTC, andrewconnell commented
It isn't? I merged your changes... what's missing? If there's an issue, can you create an issue, self-assign and a new PR that closes it?

I had to squash your commits into one as we only merge a PR as a single commit... I might have made a mistake in that as there were a lot of conflicts between your multiple commits.

2017-02-08 11:54 UTC, emilverwoerd commented
well the file 'tableDirective.spec.ts' wasn't updated for the rest it looks quite good so I could add a PR and fix it.

2017-02-08 11:58 UTC, andrewconnell commented
My bad... would you mind creating an issue documenting the problem? While I let this one pass, we really want every PR to be tied to an issue.